defaults:
  deploy_cmd: gem push *.gem
  before_deploy_cmds:
    - /usr/local/bin/op tag-release
    - sed -i "" -e "s/\".*/\"$(git tag| sed s/v// | sort -n -t. -k1,1 -k2,2 -k3,3 | tail -1)\"/" lib/hubstats/version.rb
    - git add  lib/hubstats/version.rb
    - git commit -m "Version Bump" && git push
    - gem build hubstats.gemspec
  after_deploy_cmds:
    - rm *.gem
environments:
  -
    rubygems: {}
